export { default as Home } from './Home.vue'
export { default as Mail } from './Mail.vue'
export { default as Contact } from './Contact.vue'
export { default as Logo } from './Logo.vue'
export { default as Permission } from './Permission.vue'
export { default as Dashboard } from './Dashboard.vue'